<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MvCameraControl.Net" Version="1.1.0" />
    <PackageReference Include="OpenCVSharp" Version="2.4.0.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260302" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MvCameraControl.Net">
      <HintPath>..\..\..\dll\MvCameraControl.Net.dll</HintPath>
    </Reference>
    <Reference Include="OpenCvSharp">
      <HintPath>bin\x64\Debug\net10.0-windows7.0\OpenCvSharp.dll</HintPath>
    </Reference>
    <Reference Include="OpenCvSharp.Extensions">
      <HintPath>bin\x64\Debug\net10.0-windows7.0\OpenCvSharp.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="OpenCvSharp.WpfExtensions">
      <HintPath>bin\x64\Debug\net10.0-windows7.0\OpenCvSharp.WpfExtensions.dll</HintPath>
    </Reference>
    <Reference Include="PackVisionApp">
      <HintPath>bin\x64\Debug\net10.0-windows7.0\PackVisionApp.dll</HintPath>
    </Reference>
    <Reference Include="zxing">
      <HintPath>bin\x64\Debug\net10.0-windows7.0\zxing.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utils\" />
  </ItemGroup>

</Project>