<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260318" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260302" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

</Project>